feat(poweredBy): update component logo
algolia/react-instantsearch pull request #3661
Opened 2022-10-21 10:56 UTC by FabienMotte

**Summary**

This PR updates the SVG of the `<PoweredBy>` widget component for `react-instantsearch-dom` and `react-instantsearch-hooks-web` and test snapshots.

2022-10-21 11:09 UTC, sarahdayan commented
I see a missing space between the text and logo on React InstantSearch v6.

![Capture d’écran 2022-10-21 à 13 09 25](https://user-images.githubusercontent.com/5370675/197182571-a865d350-ec46-45bf-85b5-d70e2dd0ef79.png)

2022-10-21 11:19 UTC, FabienMotte commented
> I see a missing space between the text and logo on React InstantSearch v6 ([sandbox](https://codesandbox.io/s/react-instantsearch-app-forked-e7r6fs)).
> 
> ![Capture d’écran 2022-10-21 à 13 09 25](https://user-images.githubusercontent.com/5370675/197182571-a865d350-ec46-45bf-85b5-d70e2dd0ef79.png)

It looks like we have a `margin-left: 0.3rem` on RIS Storybook but I'm not sure where that's coming from
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/662153/197183993-cef275d2-b74f-4535-b71d-ec3651fb4a64.png">

2022-10-21 11:29 UTC, sarahdayan commented
@FabienMotte It's from the Algolia theme: https://github.com/algolia/instantsearch-specs/blob/3044c2b7c99e7637403c8a2ea2ff70ec4d112f95/src/styles/themes/algolia.scss#L464-L466 while the [sandbox](https://codesandbox.io/s/react-instantsearch-app-forked-wmw1yb) uses the Satellite theme.

2022-10-21 11:32 UTC, FabienMotte commented
> @FabienMotte It's from the [Algolia theme](https://github.com/algolia/instantsearch-specs/blob/3044c2b7c99e7637403c8a2ea2ff70ec4d112f95/src/styles/themes/algolia.scss#L464-L466) while the [sandbox](https://codesandbox.io/s/react-instantsearch-app-forked-wmw1yb) uses the Satellite theme.

Oh I see, so we had the issue before: https://codesandbox.io/s/react-instantsearch-app-forked-xyf9lu
How do you think we should solve this?

2022-10-24 15:07 UTC, Haroenv commented on packages/react-instantsearch-dom/src/components/PoweredBy.js
> +  <svg viewBox="0 0 512 117" className={cx('logo')}>
the same height IMO

2022-10-25 08:04 UTC, Haroenv requested changes
leaving a review so I know when height is added again :)

2022-10-25 08:09 UTC, sarahdayan commented
@FabienMotte Since the issue was already here, we can fix it separately.

Let's make sure we constrain the size of the SVG in this PR, then feel free to open another one to add the margin (can be done after this one is merged).

2022-10-25 08:16 UTC, FabienMotte commented on packages/react-instantsearch-dom/src/components/PoweredBy.js
> +  <svg viewBox="0 0 512 117" className={cx('logo')}>
Thanks to both of you!

2022-10-25 08:49 UTC, Haroenv commented
looks like the examples test snapshot needs to be updated: https://app.circleci.com/pipelines/github/algolia/react-instantsearch/3384/workflows/73addfe9-b508-4795-9235-d40303bc5934/jobs/58582

2022-10-25 08:55 UTC, FabienMotte commented
@Haroenv I did update them but forgot to build before, doing it right now

2022-10-25 09:33 UTC, Haroenv approved these changes

2022-10-25 09:33 UTC, merged